services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: voipmonitor
      MARIADB_USER: voipmonitor
      MARIADB_PASSWORD: voipmonitor
    command:
      - --max-allowed-packet=100MB
      - --innodb_file_per_table=1
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
  #   volumes:
  #     - mariadb_data:/var/lib/mysql

  sniffer:
    image: ghcr.io/braams/voipmonitor-sniffer:latest
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./voipmonitor.conf:/etc/voipmonitor/voipmonitor.conf:ro
      - ./voipmonitor_data:/var/spool/voipmonitor
    ports:
      - "4789:4789/udp"
      - "1234:1234/udp"

  gui:
    image: ghcr.io/braams/voipmonitor-gui:gui
    platform: linux/amd64
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./configuration.php:/var/www/html/config/configuration.php
      - ./voipmonitor_data:/var/spool/voipmonitor
    #      - ./key.php:/var/www/html/key.php
    ports:
      - "8090:80/tcp"
